### ISSUE TITLE
Post Excerpt if Not Post Content

### ISSUE THREAD

**Issue by dshanske** [pfefferle/autonomie#11]
Related: https://github.com/snarfed/wordpress-micropub/pull/92 

If there is no post content, this theme should display the summary if set. 

To be created, a post has to have either a name, content, or an excerpt in WordPress.

**Comment by pfefferle** [comment]
This breaks almost all Themes, I am not sure it is a good pattern to use only the excerpt. Will think about it.

**Comment by Cambridgeport90** [comment]
I think the flaw is with Wordpress itself.
