### ISSUE TITLE
max-width not applied to search result post summaries

### ISSUE THREAD

**Issue by MrKapowski** [pfefferle/Autonomie#23]
Example: https://mrkapowski.com/?s=test
Autonomie version: **1.0.0-beta-2 (.zip downloaded 15-May-2019)**

Search results with auto-generated excerpts from`<?php the_excerpt(); ?>` are not wrapped in any HTML tags, so they are not triggering the `.entry-summary > *` rule from default-width.css, resulting in the excerpt extending the full width of the screen.

Example output:

```html
<div class="entry-summary p-summary entry-title p-name" itemprop="name description articleBody">
    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora quas, natus quod eaque vel esse debitis inventore culpa ea ullam saepe iure ab nostrum in. Commodi quaerat ullam quidem minima.…</div>
```

If the excerpt was wrapped in anything (p, span, whatever) then the correct max-width would be applied:

```html
<div class="entry-summary p-summary entry-title p-name" itemprop="name description articleBody">
    <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Tempora quas, natus quod eaque vel esse debitis inventore culpa ea ullam saepe iure ab nostrum in. Commodi quaerat ullam quidem minima…</p></div>
```

**Comment by pfefferle** [comment]
do you have an example page for me, because it is working smoothly on my site: https://notiz.blog/?s=openid

**Comment by pfefferle** [comment]
Oh, sorry... haven't seen the link!

**Comment by pfefferle** [comment]
It may be a problem with the `classic editor` and the `post-kinds` plugin!?!

**Comment by MrKapowski** [comment]
I’ll be able to dig into things more from my side, when I get home in a couple of hours. I’m a bit restricted at the office. I’ll try disabling both plugins as a first step, and report back. I’m running the latest versions of both, FWIW.

**Comment by MrKapowski** [comment]
The problem does indeed disappear if I disable the Post Kinds plugin. It seems obvious now I've noticed the double output of Kind metadata in the search results as well.

While I was at it, I had a look at my previous theme, and it made use of `remove_filter( 'the_excerpt', array( 'Kind_View', 'excerpt_response' ), 20 );` to remove Post Kinds from `the_excerpt()` output. I'll add this to a child theme of Autonomie, to solve my immediate problem 🙂

Should I close this issue, or do you want me to leave it open for now?

**Comment by pfefferle** [comment]
I would keep it open for documentation. Have you filed a bug on the Post-Kinds repo?

**Comment by MrKapowski** [comment]
Yes, I've just created it. Thank you for taking a look at this and pointing me in the right direction :+1:

**Comment by pfefferle** [comment]
No problem and I am glad that you like/use the theme! 😊

**Comment by pfefferle** [comment]
Oh, nice! Thanks @MrKapowski and @dshanske! It looks really nice now!
