### ISSUE TITLE
Odd child theme behaviour

### ISSUE THREAD

**Issue by billbennettnz** [pfefferle/autonomie#25]
I like to set up WordPress themes with a child theme. 

This runs into a problem with Autonomie

If I use this for the child  css:

/*
Theme Name: Autonomie-child
Description: Indieweb chld theme
Template: Autonomie-master
Version: 1.0.0
*/

and this for the child functions.php 

<?php
//Child Theme Functions File

add_action( 'wp_enqueue_scripts', 'enqueue_parent_styles' );

function enqueue_parent_styles() {
   wp_enqueue_style( 'parent-style', get_template_directory_uri()  . '/style.css' );
}

The activated child theme runs the body text across the width of the screen and runs the top of page menu across a narrower measure than the parent. These are plain vanilla child theme files, I've not added a thing at this stage.

**Comment by MrKapowski** [comment]
@billbennettnz your issue seems to have been cut-off, as there's nothing about your functions.php or what's actually going wrong?

**Comment by billbennettnz** [comment]
So I did. 

What I meant to say is this picks up some, but not all, the CSS formatting. In particular post text in the child theme version extends to the edges of the screen, unlike in the theme itself. Also the menu at the top busts onto a new line, it doesn’t do this in the master theme. 

I suspect the problem is to do with the responsive screen elements being stored in a separate css file, but I don’t know how to enqueue this in the function.php file.

Presumably coders will find this trivial, I don’t. Think of me as representing the non-coding audience.

**Comment by MrKapowski** [comment]
I ran into this myself. What I ended up doing is copying and overriding the entire `autonomie_setup()` function, to get all of the required stylesheets. You can see how I've done it here: https://github.com/MrKapowski/Autonomie-child/blob/master/functions.php

Hope this helps you out!

**Comment by billbennettnz** [comment]
Thanks Chris, that's exactly what I needed. I think I could have worked out a crude way to manually enqueue each of the CSS files in the CSS folder, but I doubt I'd ever have blundered my way to the twiddly bits.

**Comment by SpencerDub** [comment]
I had this same issue, and copying the entire `autonomie_enqueue_scripts()` function from @MrKapowski's child theme solved it. Thanks for sharing it, Chris, and thanks @billbennettnz for raising the issue.

**Comment by billbennettnz** [comment]
> I ran into this myself. What I ended up doing is copying and overriding the entire `autonomie_enqueue_scripts()` function, to get all of the required stylesheets. You can see how I've done it here: https://github.com/MrKapowski/Autonomie-child/blob/master/functions.php
> 
> Hope this helps you out!

Would it be possible to reprint this code? I lost my original version.

**Comment by billbennettnz** [comment]
> I had this same issue, and copying the entire `autonomie_enqueue_scripts()` function from @MrKapowski's child theme solved it. Thanks for sharing it, Chris, and thanks @billbennettnz for raising the issue.

Would it be possible to reprint this code? I lost my original version.

**Comment by MrKapowski** [comment]
Hi @billbennettnz - hopfully the code below helps. It was taken from the backup of my site before I archived it, so should be the most up-to-date version:

````
function autonomie_enqueue_scripts() {
    /*
        * Adds JavaScript to pages with the comment form to support sites with
        * threaded comments (when in use).
        */
    if ( is_singular() && comments_open() && get_option( 'thread_comments' ) ) {
        wp_enqueue_script( 'comment-reply' );
    }

    // Add  support to older versions of IE
    if ( isset( $_SERVER['HTTP_USER_AGENT'] ) &&
        ( false !== strpos( $_SERVER['HTTP_USER_AGENT'], 'MSIE' ) ) &&
        ( false === strpos( $_SERVER['HTTP_USER_AGENT'], 'MSIE 9' ) ) ) {

        wp_enqueue_script( '', get_template_directory_uri() . '/assets/js/html5shiv.min.js', false, '3.7.3' );
    }

    wp_enqueue_script( 'autonomie-navigation', get_template_directory_uri() . '/assets/js/navigation.js', array(), '1.0.0', true );
    wp_enqueue_script( 'autonomie-skip-link-focus-fix', get_template_directory_uri() . '/assets//js/skip-link-focus-fix.js', array(), '1.0.0', true );

    wp_enqueue_style( 'dashicons' );

    // Loads our main stylesheet.
    wp_enqueue_style( 'autonomie-style', get_template_directory_uri() . '/style.css', array( 'dashicons' ) );
    wp_enqueue_style( 'autonomie-print-style', get_template_directory_uri() . '/assets/css/print.css', array( 'autonomie-style' ), '1.0.0', 'print' );
    wp_enqueue_style( 'autonomie-narrow-style', get_template_directory_uri() . '/assets/css/narrow-width.css', array( 'autonomie-style' ), '1.0.0', '(max-width: 800px)' );
    wp_enqueue_style( 'autonomie-default-style', get_template_directory_uri() . '/assets/css/default-width.css', array( 'autonomie-style' ), '1.0.0', '(min-width: 800px)' );
    wp_enqueue_style( 'autonomie-wide-style', get_template_directory_uri() . '/assets/css/wide-width.css', array( 'autonomie-style' ), '1.0.0', '(min-width: 1000px)' );
    wp_enqueue_style( 'autonomie-child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array( 'autonomie-style' ),
        wp_get_theme()->get('Version')
    );

    wp_localize_script(
        'autonomie',
        'vars',
        array(
            'template_url' => get_template_directory_uri(),
        )
    );

    if ( has_header_image() ) {
        if ( is_author() ) {
            $css = '.page-banner {
                background: linear-gradient(rgba(0, 0, 0, 0.4), rgba(0, 0, 0, 0.7)), url(' . get_header_image() . ') no-repeat center center scroll;
            }' . PHP_EOL;
        } else {
            $css = '.page-banner {
                background: linear-gradient(rgba(0, 0, 0, 0.1), rgba(0, 0, 0, 0.7)), url(' . get_header_image() . ') no-repeat center center scroll;
            }' . PHP_EOL;
        }

        wp_add_inline_style( 'autonomie-style', $css );
    }
}
````
I'd been tidying up repositories I thought were no longer needed, but I can reupload the whole Child Theme again after Christmas.

**Comment by billbennettnz** [comment]
Thanks so much.

I went down a different path for a while, but have wanted to get back to the indieweb model for months and found I’d accidentally killed all my archives.

**Comment by billbennettnz** [comment]
Hi Chris

Do you still have that child theme?

For some reason I can’t get mine to work so my site is running off a hacked
version of the master, which is not ideal.

No worries if you don’t. It’s not as if the existing set up doesn’t work.


Bill Bennett

Mobile: +064 27508 2740
Email: ***@***.***
https://billbennett.co.nz
