### ISSUE TITLE
Position of imported maps.

### ISSUE THREAD

**Issue by stephenpieper** [pfefferle/Autonomie#27]
I really like this theme but there's one little problem I can't seem to fix. I use David Shanske's  Simple Location plugin to pull in maps but the maps are stuck to the left side of the post page. I can't find the best solution to center them without affecting something else. Is there a good way to do this?

Here's an example: https://stephenpieper.net/7217-2/

**Comment by pfefferle** [comment]
Should be fixed with the latest commit.

**Comment by stephenpieper** [comment]
Perfect. Thank you.
