### ISSUE TITLE
Conflict with Yoast SEO

### ISSUE THREAD

**Issue by billbennettnz** [pfefferle/Autonomie#29]
I don't need Yoast, so this is not critical, but when testing Yoast SEO I ran into the following error:

Google Search Console warns there is a “Unparsable structured data” on some of my pages. It reports:

Incorrect value type “@id”

If I dig into the error I find this code:

`{"@type":"WebPage","@id":false,"url":false,"name":"0 &ndash; Page 3 of 298 &ndash; Bill Bennett"}}]}]}</script>
`

The page where the error is flagged is: https://billbennett.co.nz/type/standard/page/5/

There's a support thread about this on the Wordpress.org site: 

https://wordpress.org/support/topic/incorrect-value-type-id-3/#post-12387557

As I said, this isn't a big deal for me... I intend to kill Yoast soon and don't care about SEO, but it could indicate a problem elsewhere. Or not. Would be interested to hear either way.

**Comment by pfefferle** [comment]
Hmm, good to know! I will re-test the schema.org integration. It feels that they change the spec every half a year :(

**Comment by pfefferle** [comment]
I re-checked your page and the error is produced by a line, that is added by YOAST. Can you disable the schema.org integration of YOAST?

**Comment by billbennettnz** [comment]
I checked out the documentation and it look possible, but means diving into the plug-in code. At this point I'm out of my depth. 

This is what it says at the support site:

To disable Schema entirely

If you return false or an empty array on the wpseo_json_ld_output filter, you disable all Yoast SEO's schema output.

add_filter( 'wpseo_json_ld_output', '__return_false' );

I have no idea WHERE to insert this code. I don't even know which file to insert it into.

**Comment by pfefferle** [comment]
I can add it to the theme, but would you expect Autonomie to do so? After all, Autonomie does support schema.org natively.

**Comment by billbennettnz** [comment]
No, don't do that. It's not what I expect of the theme. I can live without Yoast...

**Comment by pfefferle** [comment]
Should we close the issue then?

**Comment by billbennettnz** [comment]
Yes.
