### ISSUE TITLE
Curious new build behaviour, almost certainly user error but reportable 

### ISSUE THREAD

**Issue by billbennettnz** [pfefferle/autonomie#30]
I swapped the latest version of Autonomie-Master for the late 2019 version using FTP. 

It broke my site. I fixed the problem by reinstating the CSS, Font and JS folders in the top level directory, the newer build at Github stores these in the assets directory.

**Comment by pfefferle** [comment]
I saw, that you are using a CDN. Is it possible to reset the CDN? I have tested it several times and I am running the latest version of Autonomie on notiz.blog and I have no issues like that.

**Comment by billbennettnz** [comment]
I use a managed host, which makes that harder as I may be offline a while waiting for the refresh.

**Comment by pfefferle** [comment]
Oh, OK! Can you keep me up to date if something changes? Where do you host?

**Comment by billbennettnz** [comment]
Pressable.
