### ISSUE TITLE
Featured images are only displaying as 88x88 thumbnails

### ISSUE THREAD

**Issue by SpencerDub** [pfefferle/Autonomie#31]
I'm hoping you can help me troubleshoot this issue that appears with Autonomie (and, strangely, the Twenty Twenty theme as well).

I have assigned many of my posts featured images through the post editor. In other themes, these display without issue: the featured images appear in the blog feed with the posts, and on single post pages, the featured image displays as a full-width banner.

![2020-02-18 - Brainthoughts Featured Images - Lovecraft](https://user-images.githubusercontent.com/4674927/74805293-8699ff00-5297-11ea-804f-2e1cb93a2b56.png)

But when I switch to Autonomie, these featured images only display as 88x88 thumbnails, and are not featured at all in the header banner:

![2020-02-18 - Brainthoughts Featured Images - Autonomie](https://user-images.githubusercontent.com/4674927/74805407-d973b680-5297-11ea-8324-9607c989f9d0.png)

You can see this live [on my blog](http://spencerdub.me/blog).

This behavior persists even after I have disabled *all* plugins. I have no idea where the 88x88 dimensions are coming from; that is not a defined image size in my WordPress installation as far as I can tell.

I'm confused because [notiz.blog](https://notiz.blog/2019/10/07/notizblog-svg/), which also uses Autonomie, appears to have no problem using featured images.

I'd greatly appreciate any help troubleshooting this. I very much want to start using Autonomie so I can IndieWebify my blog--but this is standing in my way. Thanks!

**Comment by pfefferle** [comment]
Hmmm, this is weird. Have you added the featured image using Autonomie or with the theme you used before?

**Comment by pfefferle** [comment]
Can you tell me the name of the theme you used before?

**Comment by SpencerDub** [comment]
The theme I used previously was Lovecraft, by Anders Norén. Before that was Pinboard.

**Comment by SpencerDub** [comment]
Good news (I think?): a new post with a newly uploaded featured image [does indeed work](https://spencerdub.me/blog/featured-image-test/). I'll try rebuilding my post thumbnails with Autonomie active.

**Comment by SpencerDub** [comment]
Rebuilding the post thumbnails did the trick, so it had nothing to do with Autonomie. Sorry to bother!

**Comment by pfefferle** [comment]
No problem! I am glad that it is not a problem of the theme 😊

Btw. There is also a checkbox, to display the image as hero header.

**Comment by SpencerDub** [comment]
I noticed that! Is there any way to set that setting for several posts at once?

**Comment by pfefferle** [comment]
There is no bulk settings page in WordPress, but you can do it on DB level, if this is an option for you...

**Comment by chrisbergr** [comment]
Late to the party but maybe [this plugin](https://wordpress.org/plugins/custom-field-bulk-editor/) can do the job to bulk edit several posts, if this hero header thing is done with custom fields.
