### ISSUE TITLE
Hide post date for static pages

### ISSUE THREAD

**Issue by metbril** [pfefferle/autonomie#35]
For static pages, like https://notiz.blog/contact/ the page date is shown below the header. Since static pages (imho) don't have a publication date, it would be nice if the date could be hidden from the reader.

Do you want to consider this, whether or not as an option?

**Comment by arhayati** [comment]
May I suggest removing the avatar and name of the author? It's useless and not necessary at all.

**Comment by pfefferle** [comment]
Webmentions also support page-pings, therefore it is good to have at least the option to add them. The Google Semantic-Website checker might also return errors if the author is absent. But I can make it a setting.

**Comment by arhayati** [comment]
That would be great. It can be in the meta but not on the page. Also a box of author details is always at the bottom of of every post and page, isn't that enough?

**Comment by metbril** [comment]
In WordPress technically the post or page author can be a different user than the site owner. And for the IndieWeb, a person card for the page AND each h-entry should be there.

As for the date, that can be hidden. As a workaround I might try to trick a hidden attribute with custom CSS, but a change to the template would be preferred.

**Comment by arhayati** [comment]
Great. Another thing, how can we update the theme? When a issue is solved and/or a pull request is merged, how can we have them?

**Comment by metbril** [comment]
You basically have 2 options @arhayati. 

1. Download the zip to your webhost and extract the folder with files to your themes folder.

2. SSH into your webhost, clone the repo to the theme folder and pull any changes from master. 

More info by search

https://duckduckgo.com/?q=manual+install+wordpress+theme

**Comment by pfefferle** [comment]
There are two more options:

## Composer

```Bash
$ composer require pfefferle/wordpress-autonomie --save
```

and then you can automattically call:

```Bash
$ composer update
```

via cronjob for example.

## GitHub Updater

Or you use the GitHub Updater plugin: https://github.com/afragen/github-updater

**Comment by arhayati** [comment]
Hey, if you're going for this issue and putting an option to hide the author, please add an option to hide the banner under the posts and pages too. The banner with user's name and bio and "Subscribe to author feed" link. It can still be in meta of course but hidden from people to see, at our option.

**Comment by pfefferle** [comment]
I am working on adding the taxonomy and the author informations as widgets, so you will be able to simply drag and drop the boxes you want to show/hide.
