### ISSUE TITLE
Video shows twice

### ISSUE THREAD

**Issue by arhayati** [pfefferle/autonomie#36]
When you post a video and put post-kind and format Video, the published post shows the video twice. You can see an example on https://alirezahayati.com/2020/08/the-university-of-costumed-heroes-a-video-from-the-fsf/.

It's both on index page (blogroll) and specific page for the post (such as the link I provided).
![Screenshot_2020-08-08 Ali Reza Hayati](https://user-images.githubusercontent.com/64958513/89709068-4b68b680-d931-11ea-8f9b-37bacd75fee9.png)
![Screenshot_2020-08-08 The University of Costumed Heroes A video from the FSF - Ali Reza Hayati](https://user-images.githubusercontent.com/64958513/89709069-4f94d400-d931-11ea-8f83-e6817288a74d.png)

**Comment by pfefferle** [comment]
@dshanske seems more like a Post-Kinds issue?

**Comment by dshanske** [comment]
It's on my  list of  things to figure out an alternative to. If you set the video URL and also embed it in the content, you are actually adding it twice.

**Comment by pfefferle** [comment]
@arhayati I will close this, because it is a problem in combination of the Post-Kinds plugin.
