### ISSUE TITLE
Special layout for links

### ISSUE THREAD

**Issue by arhayati** [pfefferle/autonomie#40]
Hey.

It would be great if there were a special layout for links, both for IndieWeb postkinds and WordPress post formats. Currently, it shows the title and the note you wrote. It would be great if the title of the post is hyperlinked to the link you insert.

Some previous WordPress themes have this. Even one of the IndieWeb themes have this layout.

**Comment by pfefferle** [comment]
Can you link some themes, that supports such templates? How to find the correct link?

**Comment by arhayati** [comment]
Well I can't find a specific weblog right now but take a look at WordPress Twenty Twelve theme.

I guess it takes the first hyperlinked text. Here's some examples:

A post (link) when it has not-hyperlinked text too. Well it's quite ugly but can be fixed be beautiful.
![link with text in it](https://user-images.githubusercontent.com/64958513/90292170-44144200-de36-11ea-860f-886a5a6e4212.png)

A post (link) with no additional text in it:
![link without text in it](https://user-images.githubusercontent.com/64958513/90292252-6c03a580-de36-11ea-9588-d546047e5970.png)

An example of a "note/aside" IndieWeb post kind and WordPress post type:
![note](https://user-images.githubusercontent.com/64958513/90292336-89387400-de36-11ea-93c6-c3da69d39a96.png)
