### ISSUE TITLE
Last updated date

### ISSUE THREAD

**Issue by arhayati** [pfefferle/autonomie#42]
Can there be an option (that can be enabled or disabled) to show when the post or page is last updated? We have the published date, it'll be awesome if we have last updated date too.

**Comment by arhayati** [comment]
Hey.

What's holding you back from merging?

**Comment by arhayati** [comment]
Hey @pfefferle,
I hope you're well.

What's holding you back from merging?

**Comment by pfefferle** [comment]
I search for a way to enable the widgets by default (opt out).

**Comment by arhayati** [comment]
I'm no programmer, sorry but does this help?

https://wordpress.stackexchange.com/questions/16603/enabling-default-widgets-in-a-custom-theme

https://wordpress.stackexchange.com/questions/1948/enabling-widgets-by-default-in-custom-theme-development

**Comment by arhayati** [comment]
Also, @pfefferle, I just tested the new changes. Can you please widgetify the one under the title too? The one that shows avatar and the author name and the date of the post/page?

It would be awesome if we could enable/disable the author name and avatar. Also, maybe it's better to put the date next to the post type/kind. Also, I think it would be beautiful if we could show the categories/tags after the post kind/type. Here's a picture of what I have in mind:

![autonomie-sugest](https://user-images.githubusercontent.com/64958513/95354126-ed951400-0878-11eb-8252-3a0c63628cb4.jpg)

**Comment by metbril** [comment]
The author doesn't need to be visible on a per post basis but it should be included (hidden at least) for proper microformat2 support.

**Comment by arhayati** [comment]
@metbril well it can be in meta tags. Anyway, if the blog doesn't have more than one author, it's needless to put the name and avatar in every post.

Also, what do you think about adding post categories/tags and date next to post type (above the title)?

**Comment by metbril** [comment]
It's a matter of personal preference. And it's Matthias's theme...

My personal preference would be to have the title at the top and some meta data below: date (linking to permalink) and author (if not a single person website). Any other metadata like tags categories or **post types** could be below the content. 

But as I said. It's a matter of preference.

**Comment by arhayati** [comment]
@metbril I understand that. I'm just suggesting this. I think it would be nice.
