### ISSUE TITLE
GitHub Updater doesn't work

### ISSUE THREAD

**Issue by metbril** [pfefferle/Autonomie#43]
As per [your suggestion](https://github.com/pfefferle/Autonomie/issues/35#issuecomment-673657047) I tried to update the theme with the [GitHub Updater plugin](https://github.com/afragen/github-updater).

Unfortunately the theme doesn't update. I copied and extracted the ZIP early August, and the commits since do not appear at my site.

**Comment by metbril** [comment]
I fixed it myself. The theme folder name should have had a capital 'A' like `Autonomie` instead of `autonomie`.

**Comment by pfefferle** [comment]
I think I will change it the other way around, to use the lowercase folder, because that is more common.

**Comment by pfefferle** [comment]
@metbril that means, that you have to rename the folder again :(

**Comment by metbril** [comment]
The plugin author also mentioned that you should always update the version number in `style.css` with every update/release. This will trigger an update.

**Comment by pfefferle** [comment]
Good point!

**Comment by metbril** [comment]
The latest commit of `style.css` was in September, so the GitHub updater doesn't pickup your latest changes. Would you mind updating the version number from `1.0.0` to `1.0.1`?
