### ISSUE TITLE
Special layout for quotes

### ISSUE THREAD

**Issue by arhayati** [pfefferle/autonomie#46]
It would be very good if we could have a special layout for quotes. Something like a big transparent “ ” before and after the quote. Currently, quotes don't have a title shown on the post and it's great but it would be good if we could make it more fancier and different with "aside" post type.

**Comment by metbril** [comment]
Can't that just be achieved with the block editor?

**Comment by arhayati** [comment]
@metbril yes, but it's nice to make theme give layout to the quotes (post type specially) if the post doesn't have special layouts itself. It's not important that much but it can make the theme more beautiful.

**Comment by metbril** [comment]
The advantage of using blocks would be that your content doesn't depend on the theme used. So you can switch more easily in the future.

**Comment by arhayati** [comment]
@metbril yes but many still use the classic editor. Also, many people may have lot of quotes (post kind) in their blog and not able to go back one by one to edit and convert them to blocks.

I don't want to be pushy or something, I just think this would be nice.
