### ISSUE TITLE
⚠️ Issue with Adding a Feature Image

### ISSUE THREAD

**Issue by mrkrndvs** [pfefferle/autonomie#49]
I have been having issues with adding a feature image lately on [Read Write Respond](https://readwriterespond.com/). The system registers the image as it shows up in the social media preview provided by Yoast SEO.

![](https://collect.readwriterespond.com/wp-content/uploads/2020/11/autonomie-feature-image-issue-1024x389.png)

I am assuming that this somehow relates to the theme as I tested out two other themes and they worked fine. I also updated to the latest version of Autonomie and am running WordPress 5.5.3

**Comment by pfefferle** [comment]
So it is registered, but you can't see it in the editor?

**Comment by pfefferle** [comment]
@mrkrndvs you are using the classic editor?

**Comment by mrkrndvs** [comment]
I am using classic editor. It seems to be registering, but it does not seem
to be saving.
---

Read Write Respond <https://readwriterespond.com/newsletter-archive/>

**Comment by pfefferle** [comment]
I am not using the classic editor on my site, so it might be broken. There is some logic to make the image to a hero image, perhaps this breaks the functionality. I will have a look! Thanks for reporting.
