### ISSUE TITLE
New widget area in footer

### ISSUE THREAD

**Issue by arhayati** [pfefferle/autonomie#52]
It would be nice to add a text (or html) widget in the footer above or under the WordPress and Autonomie note so people can add a copyright notice there. I'll attach a picture to show what I mean.

![Screenshot_2021-04-11 Ali Reza Hayati](https://user-images.githubusercontent.com/64958513/114304219-07b9e400-9aa0-11eb-8291-4e6e25dcde19.png)

**Comment by Cambridgeport90** [comment]
Totally agree with this.

From: Ali Reza Hayati ***@***.***>
Sent: Sunday, April 11, 2021 08:30
To: pfefferle/autonomie ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [pfefferle/autonomie] New widget area in footer (#52)


It would be nice to add a text (or html) widget in the footer above or under the WordPress and Autonomie note so people can add a copyright notice there. I'll attach a picture to show what I mean.

[Screenshot_2021-04-11 Ali Reza Hayati]<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fuser-images.githubusercontent.com%2F64958513%2F114304219-07b9e400-9aa0-11eb-8291-4e6e25dcde19.png&data=04%7C01%7C%7C9f0f6f52290b4a04135808d8fce580df%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637537409919069761%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=vrTaGn5WEfkSlJXBE2n16mFjIpSaVSfT%2BkLvgTeUcKQ%3D&reserved=0>

-

**Comment by 0xarh** [comment]
Matthias, what do you think about this?

**Comment by metbril** [comment]
Not sure but there already is a do_action in footer.php. So you could do this with a child theme already?

**Comment by Cambridgeport90** [comment]
I always thought there was a way of doing this already?

**Comment by pfefferle** [comment]
If it is only to show something, there is the `autonomie_credits` action: https://github.com/pfefferle/autonomie/blob/master/footer.php#L30

**Comment by arhayati** [comment]
Well I was thinking about something simple for those who are not expert at WordPress when I opened this ticket.

**Comment by Cambridgeport90** [comment]
Interesting… I haven’t learned about actions quite yet… still learning. I take it that’s something you can edit the PHP files themselves to get the theme to show more than what you can do in the browser?

**Comment by pfefferle** [comment]
I see.
