### ISSUE TITLE
Recent posts without titles show as "untitled"

### ISSUE THREAD

**Issue by Cambridgeport90** [pfefferle/autonomie#54]
Using the latest update of the theme, and I'm not sure whether this is something that I have to go into the PHP files and fix myself, which I can, but if I'm missing something, let me know. Recent posts that do not have titles; notes, theck ins, reads, and so on do not have titles, so Wordpress displays "untitled" on the recents, and probably on the RSS, too, though I haven't looked. If there is a way of fixing this, how? I want just the first few characters of the note itself to show.

**Comment by ScootRay** [comment]
An easy way is to edit the functions.php file in Wordpress (or use a snippets plugin like Woody snippets) and pop this in below. What you'd do is add the post formats you want the titles removed from.

```
/// Remove titles from asides/images/links from RSS feeds
//
function remove_status_title_rss ($title) {
  $post_format=get_post_format();
  if ($post_format == "aside" || $post_format == "image" || $post_format == "link") {
    $title="";
  }
  return $title;
}

add_filter( 'the_title_rss', 'remove_status_title_rss');
```

As for other than RSS feed, there's several plugins you can install that give you the option to hide the title like https://wordpress.org/plugins/hide-page-and-post-title/

Ray

**Comment by Cambridgeport90** [comment]
That's what I couldn't seemingly come up with in my head. Not sure why. Thanks, though!
