### ISSUE TITLE
Fix the license

### ISSUE THREAD

**Issue by 0xarh** [pfefferle/autonomie#56]
The LICENSE file says the license is Expat (MIT) but the README says it's GPLv3. Please fix it. I also suggest to license it under AGPLv3+. It's the best free copyleft license for the theme.

**Comment by pfefferle** [comment]
fixed.

**Comment by 0xarh** [comment]
No it's not. I sent a pull request.

**Comment by pfefferle** [comment]
I have changed the readmes, to consistently use MIT. I will verify your suggestion to change it to AGPLv3+.

**Comment by 0xarh** [comment]
I'm not sure what "will verify your suggestion" means but if you need to understand how AGPLv3+ works, here's a gist:
+ It's free software license, meaning everybody is able to study, share, modify, and share modifications (with proper attribution to you)
+ Nobody can change the license, it'll always be libre. Nobody can make it proprietary.
+ If someone makes some changes, one should also publish the source codes of one's modified versions.
+ Doesn't matter if one is using the theme for an online service, one can't make it nonfree.
+ If another version of AGPL gets released, one can relicense the theme with the newer version (it doesn't affect you).

**Comment by pfefferle** [comment]
I had a look at the comparison page of the GPL site and it says:

> Please note that the GNU AGPL is not compatible with GPLv2.

https://www.gnu.org/licenses/license-list.en.html

And some other sources say, that it is a bit tricky: https://wordpress.stackexchange.com/questions/5/am-i-allowed-to-license-my-wordpress-theme-under-the-agpl

**Comment by arhayati** [comment]
> I had a look at the comparison page of the GPL site and it says:
> 
> > Please note that the GNU AGPL is not compatible with GPLv2.

Themes are not part of core WordPress. You can even make them proprietary. You can license your theme under AGPLv3. It doesn't need to be compatible with GPLv2.

> And some other sources say, that it is a bit tricky: https://wordpress.stackexchange.com/questions/5/am-i-allowed-to-license-my-wordpress-theme-under-the-agpl

I've read some of the responses but I still think licensing the theme under AGPLv3+.

One more thing you should keep in mind is that WordPress is licensed under GPLv2+, it means even if the new license (in the family) is not compatible with old one, you can update it at your will. I hope I explained it well.
